import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "./Provider";
import { initializeServices } from '@/app/lib/init';
import { ServiceInitializer } from "@/ServiceInitializer";
import { Header } from "./components/Header";
import { Sidebar } from "./components/Sidebar";
import { Inter } from "next/font/google";
import UserInitializer from "./components/UserInitializer";

const inter = Inter({ subsets: ['latin'] })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Provider>
          {/* <ServiceInitializer /> */}
          
                  {children}
        </Provider>
      </body>
    </html>
  );
}
