import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "./Provider";
import { initializeServices } from '@/app/lib/init';
import { ServiceInitializer } from "@/ServiceInitializer";
import { Header } from "./components/Header";
import { Sidebar } from "./components/Sidebar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Provider>
          <ServiceInitializer />
          <div className={`min-h-screen  bg-background ${inter.className}`}>
            <Header />
            <div className="flex pt-16">
              <main className="overflow-auto p-4 md:p-8 w-5/6">
                <div className="container mx-auto">

                  {children}
                </div>
              </main>

              <Sidebar />

            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
